// http://www.nytimes.com/svc/crosswords/v2/puzzle/daily-2014-06-18.json

wed = {
  "status": "OK",
  "has_more": false,
  "entitlement": "premium",
  "results": [
    {
      "puzzle_id": 8067,
      "version": null,
      "puzzle_meta": {
        "formatType": "Normal",
        "publishType": "Daily",
        "title": "",
        "printDate": "2014-06-18",
        "printDotw": 3,
        "editor": "Will Shortz",
        "copyright": "2014, The New York Times",
        "height": 15,
        "width": 15,
        "notes": [
          
        ],
        "links": [
          
        ],
        "layoutExtra": [
          
        ],
        "author": "Amy Johnson"
      },
      "puzzle_data": {
        "clues": {
          "A": [
            {
              "clueNum": 1,
              "clueStart": 0,
              "value": "Some gobblers",
              "clueEnd": 3
            },
            {
              "clueNum": 5,
              "clueStart": 5,
              "value": "Part of a fashion ensemble, maybe",
              "clueEnd": 8
            },
            {
              "clueNum": 9,
              "clueStart": 10,
              "value": "Checkout procedures",
              "clueEnd": 14
            },
            {
              "clueNum": 14,
              "clueStart": 15,
              "value": "Black-bordered news item",
              "clueEnd": 18
            },
            {
              "clueNum": 15,
              "clueStart": 20,
              "value": "Plot-listing datum",
              "clueEnd": 23
            },
            {
              "clueNum": 16,
              "clueStart": 25,
              "value": "Bindle toters",
              "clueEnd": 29
            },
            {
              "clueNum": 17,
              "clueStart": 30,
              "value": "2001 best seller about competitive Scrabble",
              "clueEnd": 38
            },
            {
              "clueNum": 19,
              "clueStart": 40,
              "value": "Scarlett's suitor",
              "clueEnd": 44
            },
            {
              "clueNum": 20,
              "clueStart": 45,
              "value": "Prefix with Freudian",
              "clueEnd": 47
            },
            {
              "clueNum": 21,
              "clueStart": 49,
              "value": "Bridal path",
              "clueEnd": 53
            },
            {
              "clueNum": 22,
              "clueStart": 55,
              "value": "Tiny bits",
              "clueEnd": 59
            },
            {
              "clueNum": 23,
              "clueStart": 63,
              "value": "Without ___ (riskily)",
              "clueEnd": 66
            },
            {
              "clueNum": 24,
              "clueStart": 68,
              "value": "Interpreter of omens",
              "clueEnd": 71
            },
            {
              "clueNum": 26,
              "clueStart": 75,
              "value": "Japanese &quot;soft art&quot; (max opening score of 92 points)",
              "clueEnd": 81
            },
            {
              "clueNum": 29,
              "clueStart": 83,
              "value": "Sounds of censure (max opening score of 80 points)",
              "clueEnd": 89
            },
            {
              "clueNum": 33,
              "clueStart": 90,
              "value": "Where to hear &quot;Bravo!&quot; and &quot;Brava!&quot;",
              "clueEnd": 94
            },
            {
              "clueNum": 34,
              "clueStart": 97,
              "value": "Fathoms",
              "clueEnd": 100
            },
            {
              "clueNum": 35,
              "clueStart": 102,
              "value": "Author Levin",
              "clueEnd": 104
            },
            {
              "clueNum": 36,
              "clueStart": 105,
              "value": "Courtroom team: Abbr.",
              "clueEnd": 108
            },
            {
              "clueNum": 37,
              "clueStart": 110,
              "value": "While away",
              "clueEnd": 114
            },
            {
              "clueNum": 39,
              "clueStart": 116,
              "value": "&quot;God is the perfect ___&quot;: Browning",
              "clueEnd": 119
            },
            {
              "clueNum": 40,
              "clueStart": 120,
              "value": "Alternative to &quot;x,&quot; in math",
              "clueEnd": 122
            },
            {
              "clueNum": 41,
              "clueStart": 124,
              "value": "Quark's place",
              "clueEnd": 127
            },
            {
              "clueNum": 42,
              "clueStart": 130,
              "value": "Feather in one's cap",
              "clueEnd": 134
            },
            {
              "clueNum": 43,
              "clueStart": 135,
              "value": "Totally inept sorts (max opening score of 104 points)",
              "clueEnd": 141
            },
            {
              "clueNum": 45,
              "clueStart": 143,
              "value": "Ran off, in a way (max opening score of 94 points)",
              "clueEnd": 149
            },
            {
              "clueNum": 47,
              "clueStart": 153,
              "value": "Fare that may be rolled",
              "clueEnd": 156
            },
            {
              "clueNum": 48,
              "clueStart": 158,
              "value": "In the thick of",
              "clueEnd": 161
            },
            {
              "clueNum": 49,
              "clueStart": 165,
              "value": "Sewing kit item",
              "clueEnd": 169
            },
            {
              "clueNum": 52,
              "clueStart": 171,
              "value": "Column style",
              "clueEnd": 175
            },
            {
              "clueNum": 54,
              "clueStart": 177,
              "value": "Napkin's place",
              "clueEnd": 179
            },
            {
              "clueNum": 57,
              "clueStart": 180,
              "value": "Wonderland cake message",
              "clueEnd": 184
            },
            {
              "clueNum": 58,
              "clueStart": 186,
              "value": "What you'd need to play 26-, 29-, 43- or 45-Across",
              "clueEnd": 194,
              "related": {
                "down": [
                  
                ],
                "across": [
                  26,
                  29,
                  43,
                  45
                ]
              }
            },
            {
              "clueNum": 60,
              "clueStart": 195,
              "value": "Some hotel lobbies",
              "clueEnd": 199
            },
            {
              "clueNum": 61,
              "clueStart": 201,
              "value": "Newport Beach isle",
              "clueEnd": 204
            },
            {
              "clueNum": 62,
              "clueStart": 206,
              "value": "A.C.L.U. part: Abbr.",
              "clueEnd": 209
            },
            {
              "clueNum": 63,
              "clueStart": 210,
              "value": "Financial resources",
              "clueEnd": 214
            },
            {
              "clueNum": 64,
              "clueStart": 216,
              "value": "M.Y.O.B. part",
              "clueEnd": 219
            },
            {
              "clueNum": 65,
              "clueStart": 221,
              "value": "Guinness word",
              "clueEnd": 224
            }
          ],
          "D": [
            {
              "clueNum": 1,
              "clueStart": 0,
              "value": "Mini-metro",
              "clueEnd": 45
            },
            {
              "clueNum": 2,
              "clueStart": 1,
              "value": "Light wind?",
              "clueEnd": 46
            },
            {
              "clueNum": 3,
              "clueStart": 2,
              "value": "Barcelona's Joan ___ Foundation",
              "clueEnd": 47
            },
            {
              "clueNum": 4,
              "clueStart": 3,
              "value": "Norm: Abbr.",
              "clueEnd": 33
            },
            {
              "clueNum": 5,
              "clueStart": 5,
              "value": "Is inconsistent",
              "clueEnd": 80
            },
            {
              "clueNum": 6,
              "clueStart": 6,
              "value": "1974 Mocedades hit whose English version is titled &quot;Touch the Wind&quot;",
              "clueEnd": 81
            },
            {
              "clueNum": 7,
              "clueStart": 7,
              "value": "One-named singer who married Heidi Klum",
              "clueEnd": 52
            },
            {
              "clueNum": 8,
              "clueStart": 8,
              "value": "Stops for a breather",
              "clueEnd": 113
            },
            {
              "clueNum": 9,
              "clueStart": 10,
              "value": "Fun house noises",
              "clueEnd": 100
            },
            {
              "clueNum": 10,
              "clueStart": 11,
              "value": "Partner in crime",
              "clueEnd": 86
            },
            {
              "clueNum": 11,
              "clueStart": 12,
              "value": "Help in crime",
              "clueEnd": 57
            },
            {
              "clueNum": 12,
              "clueStart": 13,
              "value": "&quot;___ problem!&quot;",
              "clueEnd": 58
            },
            {
              "clueNum": 13,
              "clueStart": 14,
              "value": "Former Air France fleet members, for short",
              "clueEnd": 59
            },
            {
              "clueNum": 18,
              "clueStart": 34,
              "value": "Fruity soda brand",
              "clueEnd": 94
            },
            {
              "clueNum": 23,
              "clueStart": 63,
              "value": "What snobs put on",
              "clueEnd": 108
            },
            {
              "clueNum": 25,
              "clueStart": 69,
              "value": "Abbr. before a founding date",
              "clueEnd": 114
            },
            {
              "clueNum": 26,
              "clueStart": 75,
              "value": "Steinbeck family",
              "clueEnd": 135
            },
            {
              "clueNum": 27,
              "clueStart": 76,
              "value": "On the observation deck, say",
              "clueEnd": 136
            },
            {
              "clueNum": 28,
              "clueStart": 77,
              "value": "Volkswagen model since 1979",
              "clueEnd": 137
            },
            {
              "clueNum": 30,
              "clueStart": 87,
              "value": "Wounded Knee tribe",
              "clueEnd": 147
            },
            {
              "clueNum": 31,
              "clueStart": 88,
              "value": "Sweet filling, in product names",
              "clueEnd": 148
            },
            {
              "clueNum": 32,
              "clueStart": 89,
              "value": "Full, and then some",
              "clueEnd": 149
            },
            {
              "clueNum": 34,
              "clueStart": 97,
              "value": "It has its setting",
              "clueEnd": 127
            },
            {
              "clueNum": 37,
              "clueStart": 110,
              "value": "Editor's override",
              "clueEnd": 155
            },
            {
              "clueNum": 38,
              "clueStart": 111,
              "value": "&quot;It could happen&quot;",
              "clueEnd": 216
            },
            {
              "clueNum": 39,
              "clueStart": 116,
              "value": "Lumber along",
              "clueEnd": 161
            },
            {
              "clueNum": 41,
              "clueStart": 124,
              "value": "Cousins of rhododendrons",
              "clueEnd": 214
            },
            {
              "clueNum": 42,
              "clueStart": 130,
              "value": "Balloon's undoing",
              "clueEnd": 190
            },
            {
              "clueNum": 44,
              "clueStart": 138,
              "value": "Magnify an online map",
              "clueEnd": 213
            },
            {
              "clueNum": 45,
              "clueStart": 143,
              "value": "Setting of Kubla Khan's palace",
              "clueEnd": 218
            },
            {
              "clueNum": 46,
              "clueStart": 144,
              "value": "Key of a Bach &quot;Bourr&eacute;e&quot;",
              "clueEnd": 219
            },
            {
              "clueNum": 49,
              "clueStart": 165,
              "value": "Baseball part",
              "clueEnd": 210
            },
            {
              "clueNum": 50,
              "clueStart": 166,
              "value": "Cracker topper",
              "clueEnd": 211
            },
            {
              "clueNum": 51,
              "clueStart": 167,
              "value": "___ vez (again: Sp.)",
              "clueEnd": 212
            },
            {
              "clueNum": 53,
              "clueStart": 172,
              "value": "Mixed bag",
              "clueEnd": 217
            },
            {
              "clueNum": 54,
              "clueStart": 177,
              "value": "Car that may have a bar",
              "clueEnd": 222
            },
            {
              "clueNum": 55,
              "clueStart": 178,
              "value": "Some brews",
              "clueEnd": 223
            },
            {
              "clueNum": 56,
              "clueStart": 179,
              "value": "Smart-alecky",
              "clueEnd": 224
            },
            {
              "clueNum": 59,
              "clueStart": 191,
              "value": "Pompom's place",
              "clueEnd": 221
            }
          ]
        },
        "layout": [
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1
        ],
        "answers": [
          "T",
          "O",
          "M",
          "S",
          null,
          "V",
          "E",
          "S",
          "T",
          null,
          "S",
          "C",
          "A",
          "N",
          "S",
          "O",
          "B",
          "I",
          "T",
          null,
          "A",
          "R",
          "E",
          "A",
          null,
          "H",
          "O",
          "B",
          "O",
          "S",
          "W",
          "O",
          "R",
          "D",
          "F",
          "R",
          "E",
          "A",
          "K",
          null,
          "R",
          "H",
          "E",
          "T",
          "T",
          "N",
          "E",
          "O",
          null,
          "A",
          "I",
          "S",
          "L",
          "E",
          null,
          "I",
          "O",
          "T",
          "A",
          "S",
          null,
          null,
          null,
          "A",
          "N",
          "E",
          "T",
          null,
          "S",
          "E",
          "E",
          "R",
          null,
          null,
          null,
          "J",
          "U",
          "J",
          "I",
          "T",
          "S",
          "U",
          null,
          "T",
          "S",
          "K",
          "T",
          "S",
          "K",
          "S",
          "O",
          "P",
          "E",
          "R",
          "A",
          null,
          null,
          "G",
          "E",
          "T",
          "S",
          null,
          "I",
          "R",
          "A",
          "A",
          "T",
          "T",
          "S",
          null,
          "S",
          "P",
          "E",
          "N",
          "D",
          null,
          "P",
          "O",
          "E",
          "T",
          "D",
          "O",
          "T",
          null,
          "A",
          "T",
          "O",
          "M",
          null,
          null,
          "P",
          "L",
          "U",
          "M",
          "E",
          "S",
          "P",
          "A",
          "Z",
          "Z",
          "E",
          "S",
          null,
          "X",
          "E",
          "R",
          "O",
          "X",
          "E",
          "D",
          null,
          null,
          null,
          "O",
          "A",
          "T",
          "S",
          null,
          "A",
          "M",
          "I",
          "D",
          null,
          null,
          null,
          "S",
          "P",
          "O",
          "O",
          "L",
          null,
          "I",
          "O",
          "N",
          "I",
          "C",
          null,
          "L",
          "A",
          "P",
          "E",
          "A",
          "T",
          "M",
          "E",
          null,
          "B",
          "L",
          "A",
          "N",
          "K",
          "T",
          "I",
          "L",
          "E",
          "A",
          "T",
          "R",
          "I",
          "A",
          null,
          "L",
          "I",
          "D",
          "O",
          null,
          "A",
          "M",
          "E",
          "R",
          "M",
          "E",
          "A",
          "N",
          "S",
          null,
          "Y",
          "O",
          "U",
          "R",
          null,
          "M",
          "O",
          "S",
          "T"
        ]
      },
      "print_date": "2014-06-18",
      "enhanced_tier_date": null,
      "authors": [
        "Amy Johnson"
      ]
    }
  ]
}

